<center style="padding:1rem 0;">
    <h1 style="font-size: 4rem;">IA - Deep Learning</h1>
    <h2 style="font-size: 2rem;">Livrable 3 - Optimisation avancée, MLOPS et IA Explicable</h2>
    <h5 style="font-size: 1rem;"><i>Thomas VINET, Hugo HELM, Alban GODIER</i></h5>
</center>

<img src="assets/cesi.png" style="position:absolute;right:2rem;top:4.5rem;width:10rem;background:#fee237;"/>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

import shap

from lib.neural_network.explainatinator.shap import SHAP
from lib.neural_network.neural_network import NeuralNetwork
from lib.neural_network.layer import Layer
from lib.neural_network.activation.relu import Relu
from lib.neural_network.activation.sigmoid import Sigmoid
from lib.neural_network.loss.mean_squared_error import MeanSquaredError

np.random.seed(42)

# Model

In [2]:
data = pd.read_csv("C:\\Users\\HELM\\dossier_perso\\source\\A4\\deep_learning\\porject\\CESI_A4_IA_DeepLearning\\dataset\\dataset_train.csv")

data.head()

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,DiffWalk,Sex,Age
0,0.0,0.0,0.0,1.0,0.31250,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.750000
1,0.0,1.0,0.0,1.0,0.34375,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.000000
2,1.0,1.0,1.0,1.0,0.75000,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.750000
3,1.0,1.0,0.0,1.0,0.53125,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.916667
4,0.0,1.0,1.0,1.0,0.43750,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.000000


In [3]:
target = "Diabetes_binary"
x_data = data.drop(columns=[target]).values
y_data = data[target].values

print(x_data.shape)

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

(59582, 16)


In [4]:
nn = NeuralNetwork(
    layers=[
        Layer(neurons=32, activation=Relu()),
        Layer(neurons=16, activation=Relu()),
        Layer(neurons=1, activation=Sigmoid()),
    ],
    loss=MeanSquaredError(),
    inputs=16
)

nn.fit(x_train, y_train, epochs=10)

In [5]:
shap_explain_gay = SHAP(model=nn, data=x_train[:100], num_groups=100)

x_explain = x_test[:5]
print(x_explain.shape)

explainatinations = shap_explain_gay.explain(x_explain)

(5, 16)
[(np.int64(12),), (np.int64(7), np.int64(11), np.int64(12), np.int64(4), np.int64(10), np.int64(3), np.int64(1), np.int64(14), np.int64(2), np.int64(13)), (np.int64(13), np.int64(12)), (np.int64(2), np.int64(6), np.int64(12), np.int64(9), np.int64(4), np.int64(13)), (np.int64(11), np.int64(15), np.int64(8), np.int64(3)), (np.int64(8), np.int64(7), np.int64(3), np.int64(6), np.int64(11), np.int64(9), np.int64(10)), (np.int64(9), np.int64(7), np.int64(2), np.int64(13), np.int64(1), np.int64(14), np.int64(3), np.int64(5), np.int64(10), np.int64(12), np.int64(11), np.int64(4), np.int64(6), np.int64(8)), (np.int64(2), np.int64(3), np.int64(13), np.int64(8), np.int64(15), np.int64(6), np.int64(9), np.int64(10), np.int64(11), np.int64(4), np.int64(12), np.int64(5)), (np.int64(1), np.int64(5), np.int64(4), np.int64(7), np.int64(14), np.int64(6), np.int64(2), np.int64(13)), (np.int64(5), np.int64(14), np.int64(9), np.int64(7), np.int64(10), np.int64(8), np.int64(4), np.int64(15), np.int

In [9]:
print(explainatinations)

[[ 0.04068745  0.02570385  0.02305777 -0.05490812 -0.02601995  0.00212315
  -0.01634501 -0.04224173  0.01966617  0.01756779  0.0122818   0.00300424
  -0.00683546  0.0012457   0.03909107  0.03577651]
 [ 0.06525994  0.01258944 -0.01008889 -0.00417349  0.00620485 -0.0777184
  -0.04856945 -0.02220429  0.044936    0.0300458  -0.04461738  0.01999899
   0.02423397  0.08262695 -0.00522701  0.01695861]
 [-0.04176046 -0.0153956  -0.01621202 -0.10973915 -0.01993626 -0.01047183
  -0.01636967 -0.0309849  -0.03853835 -0.0326136  -0.04369833 -0.05175911
  -0.02419986  0.00385967 -0.03813311 -0.0375716 ]
 [-0.04029235 -0.03029776 -0.03598716  0.04067449  0.0420761  -0.09013844
   0.02508918  0.06379052  0.05813049 -0.00477386 -0.0170669  -0.01849743
  -0.05437207 -0.06820015  0.06858654 -0.03213586]
 [-0.04438851 -0.03228736 -0.06146087  0.05753666  0.04088015  0.01674711
  -0.04201156  0.02466225 -0.00369912  0.0027308   0.08136647  0.01845364
   0.00594397 -0.04864509  0.02001471 -0.2080651 ]]


In [7]:
# test with shap library

def predict_fn(X):
    preds = nn.predict(X)
    return preds.reshape(-1, 1)

explainer = shap.KernelExplainer(predict_fn, x_train[:100])
shap_values = explainer.shap_values(x_explain)
print(shap_values)

  0%|          | 0/5 [00:00<?, ?it/s]

[[[ 0.26185819]
  [ 0.21156036]
  [ 0.        ]
  [-0.1332094 ]
  [ 0.        ]
  [ 0.09908727]
  [-0.01990746]
  [-0.02655142]
  [-0.01715575]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [-0.0481627 ]
  [ 0.0470188 ]
  [ 0.21546211]]

 [[ 0.26760009]
  [ 0.11890812]
  [ 0.00731653]
  [ 0.01895405]
  [ 0.        ]
  [ 0.        ]
  [-0.01574607]
  [-0.02374996]
  [-0.02430503]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.15999335]
  [-0.04357963]
  [ 0.12460854]]

 [[-0.11053318]
  [-0.06744331]
  [ 0.        ]
  [-0.15252525]
  [ 0.        ]
  [-0.00312967]
  [-0.01734632]
  [-0.00798309]
  [-0.00439625]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [-0.00312832]
  [-0.03099258]
  [-0.01252202]
  [ 0.        ]]

 [[-0.14196898]
  [-0.06489209]
  [ 0.        ]
  [ 0.00980674]
  [-0.00633753]
  [-0.00680132]
  [-0.02466764]
  [-0.00711798]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [ 0.        ]
  [-0.04644681]
  

In [8]:
test = np.array([[0.5, 0.2, 0.1], [0.3, 0.4, 0.2]])
print(test[:, [0, 1]])
print(np.mean(test[:, [0, 1]], axis=0, keepdims=True))

[[0.5 0.2]
 [0.3 0.4]]
[[0.4 0.3]]
